### PR TITLE
Dev framework notebooks refer to `model` instead of `project` in `vm.init()`

### PR DESCRIPTION
**Pull request by panchicore**
## Internal Notes for Reviewers

Update API parameter from 'project' to 'model'

Refactored various Jupyter notebooks to replace instances of the 'project' parameter with 'model' in the validmind API initialization. This ensures consistency with the latest platform changes.

Backend solution with @johnwalz97 here: https://validmind.slack.com/archives/C04U7TKHH62/p1726776209580419

Tested on

- notebooks/code_samples/quickstart_customer_churn_full_suite.ipynb
- notebooks/code_samples/credit_risk/application_scorecard_demo.ipynb

### CODE REVIEW

**Review by johnwalz97 — APPROVED** [review]
Great work... LGTM

I would just recommend that you update the header used to `X-API-KEY` in `validmind/api_client.py`... That way you can phase out `X-PROJECT-CUID` once we're certain all clients are up to date.

**Comment by cachafla** [comment]
> Great work... LGTM
> 
> I would just recommend that you update the header used to `X-API-KEY` in `validmind/api_client.py`... That way you can phase out `X-PROJECT-CUID` once we're certain all clients are up to date.

What do you mean with `X-API-KEY` in relation to models/projects?

**Comment by johnwalz97** [comment]
> > Great work... LGTM
> > I would just recommend that you update the header used to `X-API-KEY` in `validmind/api_client.py`... That way you can phase out `X-PROJECT-CUID` once we're certain all clients are up to date.
> 
> What do you mean with `X-API-KEY` in relation to models/projects?

ah that was a typo 🤦 ... meant to say `X-MODEL-CUID` and not `X-API-KEY` @cachafla @panchicore

**Review by cachafla — APPROVED** [review]
👌

**Pull request merged**
